/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  ADAPT THIS FILE — 3 of 3
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * One entry per doc page, in the order the doc nav lists them.
 *
 * Entries are deliberately short. `docUrl`, `demoUrl` and the output filename
 * are derived from `project.config.ts` plus the fields below, so no entry can
 * point at the wrong framework's docs and filenames stay in nav order without
 * anyone numbering them by hand.
 *
 * ── Where this list came from ──────────────────────────────────────────────
 * Generated from `frontend/src/lib/nav-config.ts`, which is this app's single
 * source of truth for route -> doc-page mapping. Every route carrying
 * `hasDemo: true` is registered here, in nav order; routes without a
 * `demo-chat` page are reference material and are deliberately absent, because
 * `demoUrl` is always `route + demoSuffix` and the doctor errors on any that
 * is not 200.
 *
 * Re-derive rather than hand-edit when the nav changes, then re-check the line
 * ranges below.
 *
 * ── The line ranges ────────────────────────────────────────────────────────
 * `startLine`/`endLine` are what the simulated IDE highlights, and they drift
 * the moment someone edits a demo page. `npm run doctor` checks each range
 * points at real code; where a file carries `[!code highlight]` or `#region`
 * markers it also checks the range still covers one.
 */

import { definePages } from '../core/types';

export const PAGES = definePages([
  {
    id: "quickstart",
    name: "Getting Started - Quickstart",
    videoName: "Quickstart",
    docPath: "quickstart?agent=bring-your-own",
    route: "quickstart",
    ideFile: "frontend/package.json",
    startLine: 12,
    endLine: 28,
    extraTabs: [
      { filePath: "frontend/src/app/quickstart/demo-chat/page.tsx", startLine: 15, endLine: 35 },
      { filePath: "frontend/src/app/api/copilotkit/route.ts", startLine: 1, endLine: 35 },
      { filePath: "backend/main.py", startLine: 57, endLine: 61 },
    ],
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "prebuilt-components-chat",
    name: "Prebuilt Components - CopilotChat",
    videoName: "CopilotChat",
    docPath: "prebuilt-components/chat",
    route: "prebuilt-components/chat",
    ideFile: "frontend/src/app/prebuilt-components/chat/demo-chat/page.tsx",
    startLine: 16,
    endLine: 41,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "prebuilt-components-sidebar",
    name: "Prebuilt Components - CopilotSidebar",
    videoName: "CopilotSidebar",
    docPath: "prebuilt-components/sidebar",
    route: "prebuilt-components/sidebar",
    ideFile: "frontend/src/app/prebuilt-components/sidebar/demo-chat/page.tsx",
    startLine: 19,
    endLine: 53,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "prebuilt-components-popup",
    name: "Prebuilt Components - CopilotPopup",
    videoName: "CopilotPopup",
    docPath: "prebuilt-components/popup",
    route: "prebuilt-components/popup",
    ideFile: "frontend/src/app/prebuilt-components/popup/demo-chat/page.tsx",
    startLine: 16,
    endLine: 50,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "prebuilt-components-chat-controls",
    name: "Prebuilt Components - Open, close, and feedback",
    videoName: "OpenCloseAndFeedback",
    docPath: "prebuilt-components/chat-controls",
    route: "prebuilt-components/chat-controls",
    ideFile: "frontend/src/app/prebuilt-components/chat-controls/demo-chat/page.tsx",
    startLine: 36,
    endLine: 70,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "custom-look-and-feel-css",
    name: "Custom Look and Feel - CSS Customization",
    videoName: "CSSCustomization",
    docPath: "custom-look-and-feel/css",
    route: "custom-look-and-feel/css",
    ideFile: "frontend/src/app/custom-look-and-feel/css/demo-chat/page.tsx",
    startLine: 12,
    endLine: 31,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "custom-look-and-feel-slots",
    name: "Custom Look and Feel - Slots",
    videoName: "Slots",
    docPath: "custom-look-and-feel/slots",
    route: "custom-look-and-feel/slots",
    ideFile: "frontend/src/app/custom-look-and-feel/slots/demo-chat/page.tsx",
    startLine: 41,
    endLine: 70,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "custom-look-and-feel-headless-ui",
    name: "Custom Look and Feel - Headless UI",
    videoName: "HeadlessUI",
    docPath: "custom-look-and-feel/headless-ui",
    route: "custom-look-and-feel/headless-ui",
    ideFile: "frontend/src/app/custom-look-and-feel/headless-ui/demo-chat/page.tsx",
    startLine: 33,
    endLine: 37,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "custom-look-and-feel-reasoning-messages",
    name: "Custom Look and Feel - Reasoning Messages",
    videoName: "ReasoningMessages",
    docPath: "custom-look-and-feel/reasoning-messages",
    route: "custom-look-and-feel/reasoning-messages",
    ideFile: "frontend/src/app/custom-look-and-feel/reasoning-messages/demo-chat/page.tsx",
    startLine: 24,
    endLine: 58,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "multimodal-attachments",
    name: "Input Modalities - Multimodal Attachments",
    videoName: "MultimodalAttachments",
    docPath: "multimodal-attachments",
    route: "multimodal-attachments",
    ideFile: "frontend/src/app/multimodal-attachments/demo-chat/page.tsx",
    startLine: 23,
    endLine: 57,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "voice",
    name: "Input Modalities - Voice",
    videoName: "Voice",
    docPath: "voice",
    route: "voice",
    ideFile: "frontend/src/app/voice/demo-chat/page.tsx",
    startLine: 30,
    endLine: 54,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "generative-ui-reasoning",
    name: "Generative UI - Reasoning",
    videoName: "Reasoning",
    docPath: "generative-ui/reasoning",
    route: "generative-ui/reasoning",
    ideFile: "frontend/src/app/generative-ui/reasoning/demo-chat/page.tsx",
    startLine: 28,
    endLine: 62,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "generative-ui-tool-based",
    name: "Generative UI - Components as Tools",
    videoName: "ComponentsAsTools",
    docPath: "generative-ui/tool-based",
    route: "generative-ui/tool-based",
    ideFile: "frontend/src/app/generative-ui/tool-based/demo-chat/page.tsx",
    startLine: 34,
    endLine: 39,
    prompt: "Display a bar chart with labeled numeric values.",
    waitAfterPromptMs: 4000,
  },
  {
    id: "generative-ui-tool-rendering",
    name: "Generative UI - Tool Call Rendering",
    videoName: "ToolCallRendering",
    docPath: "generative-ui/tool-rendering",
    route: "generative-ui/tool-rendering",
    ideFile: "frontend/src/app/generative-ui/tool-rendering/demo-chat/page.tsx",
    startLine: 66,
    endLine: 93,
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "generative-ui-state-rendering",
    name: "Generative UI - State Rendering",
    videoName: "StateRendering",
    docPath: "generative-ui/state-rendering",
    route: "generative-ui/state-rendering",
    ideFile: "frontend/src/app/generative-ui/state-rendering/demo-chat/page.tsx",
    startLine: 38,
    endLine: 42,
    prompt: "Switch to Spanish",
    waitAfterPromptMs: 4000,
  },
  {
    id: "generative-ui-a2ui-dynamic-schema",
    name: "Generative UI - A2UI · Dynamic Schema",
    videoName: "A2UIDynamicSchema",
    docPath: "generative-ui/a2ui/dynamic-schema",
    route: "generative-ui/a2ui/dynamic-schema",
    ideFile: "frontend/src/app/generative-ui/a2ui/dynamic-schema/demo-chat/page.tsx",
    startLine: 26,
    endLine: 60,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "generative-ui-a2ui-fixed-schema",
    name: "Generative UI - A2UI · Fixed Schema",
    videoName: "A2UIFixedSchema",
    docPath: "generative-ui/a2ui/fixed-schema",
    route: "generative-ui/a2ui/fixed-schema",
    ideFile: "frontend/src/app/generative-ui/a2ui/fixed-schema/demo-chat/page.tsx",
    startLine: 27,
    endLine: 61,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "frontend-tools",
    name: "App Control - Frontend Tools",
    videoName: "FrontendTools",
    docPath: "frontend-tools",
    route: "frontend-tools",
    ideFile: "frontend/src/app/frontend-tools/demo-chat/page.tsx",
    startLine: 38,
    endLine: 51,
    prompt: "Change the page background.",
    waitAfterPromptMs: 4000,
  },
  {
    id: "human-in-the-loop",
    name: "App Control - Human in the Loop",
    videoName: "HumanInTheLoop",
    docPath: "human-in-the-loop",
    route: "human-in-the-loop",
    ideFile: "frontend/src/app/human-in-the-loop/demo-chat/page.tsx",
    startLine: 68,
    endLine: 90,
    prompt: "Run the command rm -rf /tmp/cache",
    waitAfterPromptMs: 4000,
  },
  {
    id: "human-in-the-loop-interrupt-flow",
    name: "App Control - Interrupts",
    videoName: "Interrupts",
    docPath: "human-in-the-loop/interrupt-flow",
    route: "human-in-the-loop/interrupt-flow",
    ideFile: "frontend/src/app/human-in-the-loop/interrupt-flow/demo-chat/page.tsx",
    startLine: 205,
    endLine: 209,
    prompt: "Run the command rm -rf /tmp/cache",
    waitAfterPromptMs: 4000,
  },
  {
    id: "programmatic-control",
    name: "App Control - Programmatic Control",
    videoName: "ProgrammaticControl",
    docPath: "programmatic-control",
    route: "programmatic-control",
    ideFile: "frontend/src/app/programmatic-control/demo-chat/page.tsx",
    startLine: 27,
    endLine: 31,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "shared-state",
    name: "Shared State - Shared State",
    videoName: "SharedState",
    docPath: "shared-state",
    route: "shared-state",
    ideFile: "frontend/src/app/shared-state/demo-chat/page.tsx",
    startLine: 47,
    endLine: 51,
    prompt: "Switch to Spanish",
    waitAfterPromptMs: 4000,
  },
  {
    id: "shared-state-rendering-in-app",
    name: "Shared State - Render state in your app",
    videoName: "RenderStateInYourApp",
    docPath: "shared-state/rendering-in-app",
    route: "shared-state/rendering-in-app",
    ideFile: "frontend/src/app/shared-state/rendering-in-app/demo-chat/page.tsx",
    startLine: 35,
    endLine: 39,
    prompt: "Switch to Spanish",
    waitAfterPromptMs: 4000,
  },
  {
    id: "shared-state-streaming",
    name: "Shared State - State Streaming",
    videoName: "StateStreaming",
    docPath: "shared-state/streaming",
    route: "shared-state/streaming",
    ideFile: "frontend/src/app/shared-state/streaming/demo-chat/page.tsx",
    startLine: 40,
    endLine: 44,
    prompt: "Switch to Spanish",
    waitAfterPromptMs: 4000,
  },
  {
    id: "shared-state-agent-readonly",
    name: "Shared State - Agent Read-Only Context",
    videoName: "AgentReadOnlyContext",
    docPath: "shared-state/agent-readonly",
    route: "shared-state/agent-readonly",
    ideFile: "frontend/src/app/shared-state/agent-readonly/demo-chat/page.tsx",
    startLine: 48,
    endLine: 59,
    prompt: "Switch to Spanish",
    waitAfterPromptMs: 4000,
  },
  {
    id: "shared-state-in-app-agent-read",
    name: "Shared State - Reading agent state",
    videoName: "ReadingAgentState",
    docPath: "shared-state/in-app-agent-read",
    route: "shared-state/in-app-agent-read",
    ideFile: "frontend/src/app/shared-state/in-app-agent-read/demo-chat/page.tsx",
    startLine: 39,
    endLine: 43,
    prompt: "Switch to Spanish",
    waitAfterPromptMs: 4000,
  },
  {
    id: "shared-state-in-app-agent-write",
    name: "Shared State - Writing agent state",
    videoName: "WritingAgentState",
    docPath: "shared-state/in-app-agent-write",
    route: "shared-state/in-app-agent-write",
    ideFile: "frontend/src/app/shared-state/in-app-agent-write/demo-chat/page.tsx",
    startLine: 35,
    endLine: 39,
    prompt: "Switch to Spanish",
    waitAfterPromptMs: 4000,
  },
  {
    id: "shared-state-state-inputs-outputs",
    name: "Shared State - Input/Output Schemas",
    videoName: "InputOutputSchemas",
    docPath: "shared-state/state-inputs-outputs",
    route: "shared-state/state-inputs-outputs",
    ideFile: "frontend/src/app/shared-state/state-inputs-outputs/demo-chat/page.tsx",
    startLine: 40,
    endLine: 44,
    prompt: "Switch to Spanish",
    waitAfterPromptMs: 4000,
  },
  {
    id: "shared-state-predictive-state-updates",
    name: "Shared State - Predictive state updates",
    videoName: "PredictiveStateUpdates",
    docPath: "shared-state/predictive-state-updates?agent-type=prebuilt",
    route: "shared-state/predictive-state-updates",
    ideFile: "frontend/src/app/shared-state/predictive-state-updates/demo-chat/page.tsx",
    startLine: 150,
    endLine: 154,
    prompt: "Switch to Spanish",
    waitAfterPromptMs: 4000,
  },
  {
    id: "multi-agent-subagents",
    name: "Multi-Agent - Sub-Agents",
    videoName: "SubAgents",
    docPath: "multi-agent/subagents",
    route: "multi-agent/subagents",
    ideFile: "frontend/src/app/multi-agent/subagents/demo-chat/page.tsx",
    startLine: 35,
    endLine: 39,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "agent-config",
    name: "LangGraph Runtime - Agent Config",
    videoName: "AgentConfig",
    docPath: "agent-config",
    route: "agent-config",
    ideFile: "frontend/src/app/agent-config/demo-chat/page.tsx",
    startLine: 103,
    endLine: 110,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "agent-app-context",
    name: "LangGraph Runtime - Readables",
    videoName: "Readables",
    docPath: "agent-app-context",
    route: "agent-app-context",
    ideFile: "frontend/src/app/agent-app-context/demo-chat/page.tsx",
    startLine: 53,
    endLine: 64,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "configurable",
    name: "LangGraph Runtime - Configurable",
    videoName: "Configurable",
    docPath: "configurable",
    route: "configurable",
    ideFile: "frontend/src/app/configurable/demo-chat/page.tsx",
    startLine: 37,
    endLine: 41,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
  {
    id: "subgraphs",
    name: "LangGraph Runtime - Subgraphs",
    videoName: "Subgraphs",
    docPath: "subgraphs",
    route: "subgraphs",
    ideFile: "frontend/src/app/subgraphs/demo-chat/page.tsx",
    startLine: 34,
    endLine: 38,
    prompt: "Can you tell me a joke?",
    waitAfterPromptMs: 4000,
  },
]);
